name: Publish package on release

on:
  release:
    types:
      - created

jobs:
  python-artifacts:
    name: Build wheel and source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build frontend
        run: pip install --upgrade hatch
      - name: Build
        run: hatch build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-artifacts
          path: dist/*
          if-no-files-found: error

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - python-artifacts
    environment:
      name: pypi
      url: https://pypi.org/p/pylemmy
    permissions:
      id-token: write
    steps:
      - name: Download Python artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-artifacts
          path: dist
      - name: Push Python artifacts to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
